In [2]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [5]:
df_1970 = df[df["year"]==1970]
df_1970[df_1970["entity"].str.startswith("K")]

          entity      code  year  life_expectancy_0
9591  Kazakhstan       KAZ  1970            60.0490
9668       Kenya       KEN  1970            54.1427
9742    Kiribati       KIR  1970            54.3802
9816      Kosovo  OWID_KOS  1970            54.0023
9891      Kuwait       KWT  1970            67.9771
9965  Kyrgyzstan       KGZ  1970            58.1840

In [7]:
df.loc[df['code'].notnull(),['entity','year','life_expectancy_0']].head(3)

        entity  year  life_expectancy_0
0  Afghanistan  1950            28.1563
1  Afghanistan  1951            28.5836
2  Afghanistan  1952            29.0138

In [ ]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()
print(df.shape)

(20217, 4)

In [14]:
resultado = (
    df.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

entity
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [29]:
df_1970_more = df[df["year"]>1970]

resultado2 = (
    df_1970_more.groupby("entity")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado2.head(10)

entity
South Sudan                 41.367542
Central African Republic    47.145481
Sierra Leone                47.397430
Chad                        47.505219
Nigeria                     47.866845
Niger                       47.939468
Somalia                     48.858694
Mali                        48.942489
Angola                      49.199087
East Timor                  49.415798
Name: life_expectancy_0, dtype: float64