In [7]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/children-born-per-woman.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/children-born-per-woman.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [8]:
df.head(3)

        entity code  year  fertility_rate_hist
0  Afghanistan  AFG  1950                7.248
1  Afghanistan  AFG  1951                7.260
2  Afghanistan  AFG  1952                7.260

In [9]:
df.shape

(19402, 4)

In [10]:
japon= df[df["entity"]=="japan"]
japon.head()

Empty DataFrame
Columns: [entity, code, year, fertility_rate_hist]
Index: []